// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Fixture interface {
	IsFixture()
}

type InterfaceFixture interface {
	IsInterfaceFixture()
}

type Basic struct {
	ID            string    `json:"id"`
	Name          *string   `json:"name"`
	Description   *string   `json:"description"`
	Installations []*string `json:"installations"`
	Opacity       int       `json:"opacity"`
	Animation     int       `json:"animation"`
	Option        int       `json:"option"`
	Speed         int       `json:"speed"`
	Strobe        int       `json:"strobe"`
}

func (Basic) IsInterfaceFixture() {}
func (Basic) IsFixture()          {}

type CreateInstallation struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type Installation struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type NewFixture struct {
	Name          *string   `json:"name"`
	Description   *string   `json:"description"`
	Installations []*string `json:"installations"`
	Type          *string   `json:"type"`
}

type Spotlight struct {
	ID            string    `json:"id"`
	Name          *string   `json:"name"`
	Description   *string   `json:"description"`
	Installations []*string `json:"installations"`
	Opacity       *int      `json:"opacity"`
}

func (Spotlight) IsInterfaceFixture() {}
func (Spotlight) IsFixture()          {}

type UpdateBasic struct {
	ID            string    `json:"id"`
	Name          *string   `json:"name"`
	Description   *string   `json:"description"`
	Installations []*string `json:"installations"`
	Opacity       *int      `json:"opacity"`
	Animation     *int      `json:"animation"`
	Option        *int      `json:"option"`
	Speed         *int      `json:"speed"`
	Strobe        *int      `json:"strobe"`
}

type UpdateInstallation struct {
	ID          string  `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type UpdateSpotlight struct {
	ID            string    `json:"id"`
	Name          *string   `json:"name"`
	Description   *string   `json:"description"`
	Installations []*string `json:"installations"`
	Opacity       *int      `json:"opacity"`
}
